#!/bin/bash
cd /home/pi/climaduino

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting climaduino-controller "
    sh start_web_controller.sh
    ;;
  stop)
    echo "Stopping climaduino-controller"
    echo "oops, can't do that"
    ;;
  *)
    echo "Usage: /etc/init.d/climaduino-controller {start|stop}"
    exit 1
    ;;
esac

exit 0
