#!/bin/bash
### BEGIN INIT INFO
# Provides:          Climaduino Controller
# Short-Description: Control component of Climaduino system
# Description:       Controls and allows users to interact with a network of environmental sensors.
### END INIT INFO

cd /home/pi/climaduino

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting climaduino-controller "
    sh start_web_controller.sh
    ;;
  stop)
    echo "Stopping climaduino-controller"
    sh stop_web_controller.sh
    ;;
    restart)
    echo "Restarting climaduino-controller"
    sh stop_web_controller.sh
    sh start_web_controller.sh
    ;;
  *)
    echo "Usage: /etc/init.d/climaduino-controller {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
