#!/bin/bash
source /home/pi/bin/activate
cd /home/pi/climaduino

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting climaduino-controller "
    /usr/bin/screen -d -m -S data-logger python manage.py runserver 0.0.0.0:80
    ;;
  stop)
    echo "Stopping climaduino-controller"
    echo "oops, can't do that"
    ;;
  *)
    echo "Usage: /etc/init.d/climaduino-controller {start|stop}"
    exit 1
    ;;
esac

exit 0
